[versions]
kotlin = "1.8.21"

kotest = "5.6.2"
mockk = "1.13.5"

[libraries]
kotest-jvm-junit = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-jvm-core = { module = "io.kotest:kotest-core-jvm", version.ref = "kotest" }
kotest-core-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }
mockk-base = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
kotest = ["kotest-jvm-junit", "kotest-jvm-core", "kotest-core-assertions"]
mockk = ["mockk-base", "mockk-jvm"]